export const SPECIALISTS = [
  {
    id: "spc-001",
    name: "Dr. Francis Adebayo",
    specialty: "Nephrologist",
    rating: 4.9,
    experience: "12 Years",
    location: "Akure, Nigeria",
    price: "₦19,000",
    image: "https://randomuser.me/api/portraits/men/18.jpg",
    timeSlots: ["08:45 AM", "10:15 AM", "12:45 PM", "03:15 PM"],
  },
  {
    id: "spc-002",
    name: "Dr. Sarah Nwachukwu",
    specialty: "Cardiologist",
    rating: 4.8,
    experience: "15 Years",
    location: "Lagos, Nigeria",
    price: "₦25,000",
    image: "https://randomuser.me/api/portraits/women/21.jpg",
    timeSlots: ["09:00 AM", "11:00 AM", "01:30 PM", "04:00 PM"],
  },
  {
    id: "spc-003",
    name: "Dr. Ibrahim Musa",
    specialty: "Dermatologist",
    rating: 4.7,
    experience: "10 Years",
    location: "Abuja, Nigeria",
    price: "₦18,500",
    image: "https://randomuser.me/api/portraits/men/12.jpg",
    timeSlots: ["08:30 AM", "10:45 AM", "01:00 PM", "03:45 PM"],
  },
  {
    id: "spc-004",
    name: "Dr. Chiamaka Eze",
    specialty: "Neurologist",
    rating: 4.9,
    experience: "14 Years",
    location: "Enugu, Nigeria",
    price: "₦28,000",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    timeSlots: ["09:15 AM", "11:15 AM", "02:00 PM", "04:15 PM"],
  },
  {
    id: "spc-005",
    name: "Dr. John Okafor",
    specialty: "Pediatrician",
    rating: 4.8,
    experience: "11 Years",
    location: "Port Harcourt, Nigeria",
    price: "₦16,000",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    timeSlots: ["08:45 AM", "10:30 AM", "01:15 PM", "03:30 PM"],
  },
  {
    id: "spc-006",
    name: "Dr. Aisha Bello",
    specialty: "Oncologist",
    rating: 4.9,
    experience: "17 Years",
    location: "Kano, Nigeria",
    price: "₦32,000",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
    timeSlots: ["09:00 AM", "11:30 AM", "01:45 PM", "04:00 PM"],
  },
  {
    id: "spc-007",
    name: "Dr. Emmanuel Olatunji",
    specialty: "Orthopedic Surgeon",
    rating: 4.7,
    experience: "13 Years",
    location: "Ibadan, Nigeria",
    price: "₦27,500",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    timeSlots: ["08:30 AM", "10:45 AM", "12:45 PM", "03:00 PM"],
  },
  {
    id: "spc-008",
    name: "Dr. Ngozi Umeh",
    specialty: "Gastroenterologist",
    rating: 4.8,
    experience: "12 Years",
    location: "Awka, Nigeria",
    price: "₦22,000",
    image: "https://randomuser.me/api/portraits/women/7.jpg",
    timeSlots: ["09:00 AM", "11:15 AM", "01:30 PM", "04:15 PM"],
  },
  {
    id: "spc-009",
    name: "Dr. Chukwudi Nnaji",
    specialty: "Pulmonologist",
    rating: 4.9,
    experience: "15 Years",
    location: "Benin City, Nigeria",
    price: "₦24,500",
    image: "https://randomuser.me/api/portraits/men/10.jpg",
    timeSlots: ["08:45 AM", "10:15 AM", "12:45 PM", "03:15 PM"],
  },
  {
    id: "spc-010",
    name: "Dr. Ifeoma Okonkwo",
    specialty: "Rheumatologist",
    rating: 4.7,
    experience: "9 Years",
    location: "Jos, Nigeria",
    price: "₦20,000",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    timeSlots: ["09:00 AM", "11:00 AM", "01:15 PM", "03:30 PM"],
  },
  {
    id: "spc-011",
    name: "Dr. Musa Abdullahi",
    specialty: "Endocrinologist",
    rating: 4.8,
    experience: "16 Years",
    location: "Sokoto, Nigeria",
    price: "₦26,000",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
    timeSlots: ["08:30 AM", "10:45 AM", "01:00 PM", "04:00 PM"],
  },
  {
    id: "spc-012",
    name: "Dr. Adesuwa Osagie",
    specialty: "Ophthalmologist",
    rating: 4.9,
    experience: "14 Years",
    location: "Benin City, Nigeria",
    price: "₦21,000",
    image: "https://randomuser.me/api/portraits/women/15.jpg",
    timeSlots: ["09:15 AM", "11:15 AM", "01:45 PM", "04:15 PM"],
  },
  {
    id: "spc-013",
    name: "Dr. Victor Balogun",
    specialty: "ENT Specialist",
    rating: 4.6,
    experience: "8 Years",
    location: "Abeokuta, Nigeria",
    price: "₦18,000",
    image: "https://randomuser.me/api/portraits/men/16.jpg",
    timeSlots: ["08:30 AM", "10:00 AM", "12:30 PM", "03:00 PM"],
  },
  {
    id: "spc-014",
    name: "Dr. Kemi Afolabi",
    specialty: "Psychiatrist",
    rating: 4.8,
    experience: "12 Years",
    location: "Lagos, Nigeria",
    price: "₦23,000",
    image: "https://randomuser.me/api/portraits/women/18.jpg",
    timeSlots: ["09:00 AM", "11:00 AM", "01:30 PM", "04:00 PM"],
  },
  {
    id: "spc-015",
    name: "Dr. Samuel Obinna",
    specialty: "General Surgeon",
    rating: 4.9,
    experience: "18 Years",
    location: "Enugu, Nigeria",
    price: "₦30,000",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
    timeSlots: ["08:45 AM", "10:15 AM", "12:45 PM", "03:15 PM"],
  },
  {
    id: "spc-016",
    name: "Dr. Halima Sani",
    specialty: "Obstetrician",
    rating: 4.8,
    experience: "11 Years",
    location: "Katsina, Nigeria",
    price: "₦19,500",
    image: "https://randomuser.me/api/portraits/women/19.jpg",
    timeSlots: ["09:00 AM", "11:30 AM", "02:00 PM", "04:15 PM"],
  },
  {
    id: "spc-017",
    name: "Dr. Peter Adeyemi",
    specialty: "Urologist",
    rating: 4.7,
    experience: "13 Years",
    location: "Osogbo, Nigeria",
    price: "₦22,500",
    image: "https://randomuser.me/api/portraits/men/20.jpg",
    timeSlots: ["08:30 AM", "10:45 AM", "01:00 PM", "03:15 PM"],
  },
  {
    id: "spc-018",
    name: "Dr. Blessing Nnamdi",
    specialty: "Hematologist",
    rating: 4.9,
    experience: "15 Years",
    location: "Uyo, Nigeria",
    price: "₦24,000",
    image: "https://randomuser.me/api/portraits/women/20.jpg",
    timeSlots: ["09:15 AM", "11:15 AM", "01:30 PM", "04:00 PM"],
  },
  {
    id: "spc-019",
    name: "Dr. Olumide Fashola",
    specialty: "Plastic Surgeon",
    rating: 4.8,
    experience: "10 Years",
    location: "Lagos, Nigeria",
    price: "₦35,000",
    image: "https://randomuser.me/api/portraits/men/21.jpg",
    timeSlots: ["08:45 AM", "10:15 AM", "12:45 PM", "03:15 PM"],
  },
  {
    id: "spc-020",
    name: "Dr. Grace Ajayi",
    specialty: "Family Physician",
    rating: 4.7,
    experience: "9 Years",
    location: "Ilorin, Nigeria",
    price: "₦17,000",
    image: "https://randomuser.me/api/portraits/women/22.jpg",
    timeSlots: ["09:00 AM", "11:00 AM", "01:15 PM", "03:30 PM"],
  },
];
