export const MEDICAL_SERVICES = [
  {
    name: "St. Mary's Medical Centre",
    type: "Hospital",
    rating: 4.8,
    reviews: 324,
    distance: "0.8 miles",
    address: "20, Healthcare Haven, Downtown",
    phone: "+234 65749756",
    emergency: true,
    specialties: ["Emergency", "Cardiology", "Orthopedics", "Neurology"],
    insuranceAccepted: true,
  },
  {
    name: "GreenLife Clinic",
    type: "Clinic",
    rating: 4.6,
    reviews: 210,
    distance: "1.2 miles",
    address: "14, Palm Street, Uptown",
    phone: "+234 7012345678",
    emergency: false,
    specialties: ["General Practice", "Pediatrics"],
    insuranceAccepted: true,
  },
  {
    name: "CityCare Hospital",
    type: "Hospital",
    rating: 4.7,
    reviews: 412,
    distance: "2.1 miles",
    address: "88, Central Avenue, City Center",
    phone: "+234 8034567890",
    emergency: true,
    specialties: ["Emergency", "Surgery", "Internal Medicine"],
    insuranceAccepted: true,
  },
  {
    name: "Sunrise Dental Clinic",
    type: "Dental",
    rating: 4.5,
    reviews: 189,
    distance: "0.9 miles",
    address: "12, Smile Road, Downtown",
    phone: "+234 8123456789",
    emergency: false,
    specialties: ["Dentistry", "Oral Surgery"],
    insuranceAccepted: true,
  },
  {
    name: "Wellness Diagnostic Center",
    type: "Diagnostic",
    rating: 4.9,
    reviews: 98,
    distance: "1.5 miles",
    address: "44, Lab Lane, Midtown",
    phone: "+234 7056781234",
    emergency: false,
    specialties: ["Radiology", "Blood Tests"],
    insuranceAccepted: true,
  },
  {
    name: "Hope Children's Hospital",
    type: "Hospital",
    rating: 4.8,
    reviews: 276,
    distance: "3.0 miles",
    address: "77, Joy Street, Eastside",
    phone: "+234 7019876543",
    emergency: true,
    specialties: ["Emergency", "Pediatrics", "Neonatology"],
    insuranceAccepted: true,
  },
  {
    name: "Healthy Heart Cardiology Center",
    type: "Specialty Clinic",
    rating: 4.7,
    reviews: 143,
    distance: "2.3 miles",
    address: "9, Artery Avenue, Southtown",
    phone: "+234 8024681357",
    emergency: false,
    specialties: ["Cardiology"],
    insuranceAccepted: true,
  },
  {
    name: "Prime Orthopedic Hospital",
    type: "Hospital",
    rating: 4.6,
    reviews: 201,
    distance: "4.1 miles",
    address: "33, Bone Street, Northside",
    phone: "+234 8156789123",
    emergency: true,
    specialties: ["Orthopedics", "Sports Medicine"],
    insuranceAccepted: true,
  },
  {
    name: "NeuroCare Institute",
    type: "Specialty Clinic",
    rating: 4.8,
    reviews: 178,
    distance: "1.8 miles",
    address: "5, Brain Boulevard, Uptown",
    phone: "+234 8076543210",
    emergency: false,
    specialties: ["Neurology", "Neurosurgery"],
    insuranceAccepted: true,
  },
  {
    name: "First Response Urgent Care",
    type: "Urgent Care",
    rating: 4.7,
    reviews: 154,
    distance: "0.6 miles",
    address: "1, Rapid Road, Downtown",
    phone: "+234 8098765432",
    emergency: true,
    specialties: ["Emergency", "General Practice"],
    insuranceAccepted: true,
  },
];
